# Generated by Django 3.2.12 on 2023-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('endereco', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=155)),
                ('telefone', models.TextField(max_length=55)),
            ],
        ),
    ]
