# Generated by Django 3.2.12 on 2023-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_coleta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='hora_coleta',
            field=models.TimeField(null=True),
        ),
    ]
